M48
; DRILL file {KiCad 7.0.11+dfsg-1} date Tue 19 Mar 2024 11:47:42 AM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-19T11:47:42-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.999
%
G90
G05
T1
X97.172Y-68.656
X132.337Y-68.656
X167.607Y-68.666
X201.897Y-68.666
M30
